[Theme]
DisplayName=Theo Cursor Image2

[Control Panel\Cursors]
Arrow=%LocalAppData%\TheoCursorImage2\Cursors\pointer.ani
Help=%LocalAppData%\TheoCursorImage2\Cursors\help.ani
AppStarting=%LocalAppData%\TheoCursorImage2\Cursors\work.ani
Wait=%LocalAppData%\TheoCursorImage2\Cursors\busy.ani
Crosshair=%LocalAppData%\TheoCursorImage2\Cursors\cross.ani
IBeam=%LocalAppData%\TheoCursorImage2\Cursors\text.ani
No=%LocalAppData%\TheoCursorImage2\Cursors\unavailable.ani
SizeNS=%LocalAppData%\TheoCursorImage2\Cursors\vert.ani
SizeWE=%LocalAppData%\TheoCursorImage2\Cursors\horz.ani
SizeNWSE=%LocalAppData%\TheoCursorImage2\Cursors\dgn1.ani
SizeNESW=%LocalAppData%\TheoCursorImage2\Cursors\dgn2.ani
SizeAll=%LocalAppData%\TheoCursorImage2\Cursors\move.ani
Hand=%LocalAppData%\TheoCursorImage2\Cursors\link.ani
